services:
  db:
    image: postgres:latest
    container_name: some-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gameDB
    ports:
      - "5433:5432"

